project:
  type: book
  output-dir: docs

book:
  title: "horror_rpg"
  author: "Pontifex Ex Machina"
  date: "4/18/2025"
  chapters:
    - index.qmd
    - game_rules.qmd
    - appendix_n.qmd

#bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook